CREATE TABLE XXFIN_USERS
(
	  user_id			NUMBER GENERATED BY DEFAULT AS IDENTITY
	, first_name		VARCHAR2(120)
	, last_name			VARCHAR2(120)
	, username          VARCHAR2(30)	NOT NULL
	, password          VARCHAR2(100)	NOT NULL
	, email             VARCHAR2(50)
	, mobile            VARCHAR2(20)
	, verified          VARCHAR2(5)	DEFAULT 'N'
	, mobile_verified	VARCHAR2(5)	DEFAULT 'N'
	, email_verified	VARCHAR2(5)	DEFAULT 'N'
	, creation_date		DATE
	, last_updated_date	DATE
	, CONSTRAINT XXFIN_USERS_PK PRIMARY KEY(user_id)
	, CONSTRAINT XXFIN_USER_ACCOUNT UNIQUE(USERNAME, EMAIL, MOBILE)
	, CONSTRAINT XXFIN_USERS_CHECK CHECK (EMAIL IS NOT NULL OR MOBILE IS NOT NULL)
)

CREATE TABLE XXFIN_TXN
(
	  txn_id			NUMBER GENERATED BY DEFAULT AS IDENTITY
	, gateway			VARCHAR2(120)
	, method            VARCHAR2(120)
	, description       VARCHAR2(240)
	, metadata          CLOB
	, status            VARCHAR2(20)
	, error_msg         VARCHAR2(500)
	, amount            NUMBER(38,2)
	, currency          VARCHAR2(50)
	, auth_id           VARCHAR2(120)	NOT NULL
	, source_id         NUMBER			NOT NULL
	, target_id         NUMBER          NOT NULL
	, txn_event         VARCHAR2(30)	NOT NULL
	, creation_date     DATE
	, created_by        VARCHAR2(120)
	, CONSTRAINT XXFIN_TXN_PK PRIMARY KEY(txn_id)
	, CONSTRAINT XXFIN_TXN_FK_SID FOREIGN KEY(source_id) REFERENCES XXFIN_USERS(user_id) 
	, CONSTRAINT XXFIN_TXN_FK_TID FOREIGN KEY(target_id) REFERENCES XXFIN_USERS(user_id) 
)